refactor(ci): use azure/cli action to run `az devops` commands

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -118,49 +118,55 @@ jobs:
 
       - name: Trigger Azure pipeline run
         id: trigger_pipeline
-        run: |
-          RUN_ID=$(az pipelines run \
-            --id "${{ secrets.ADO_PIPELINE_ID }}" \
-            --org "${{ secrets.ADO_ORG_URL }}" \
-            --project "${{ secrets.ADO_PROJECT }}" \
-            --branch "${{ github.ref }}" \
-            --commit-id ${{ github.sha }} \
-            --query "id" -o tsv)
-          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
-
-      - name: Wait for Azure pipeline run to complete
-        run: |
-          echo "Waiting for Azure DevOps Pipeline run to complete..."
-          while true; do
-            PIPELINE_STATUS=$(az pipelines runs show \
-              --id ${{ steps.trigger_pipeline.outputs.run_id }} \
+        uses: azure/cli@v2
+        with:
+          azcliversion: latest
+          inlineScript: |
+            RUN_ID=$(az pipelines run \
+              --id "${{ secrets.ADO_PIPELINE_ID }}" \
               --org "${{ secrets.ADO_ORG_URL }}" \
               --project "${{ secrets.ADO_PROJECT }}" \
-              --query "status" -o tsv)
+              --branch "${{ github.ref }}" \
+              --commit-id ${{ github.sha }} \
+              --query "id" -o tsv)
+            echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
 
-            echo "Current pipeline status: $PIPELINE_STATUS"
-
-            if [[ "$PIPELINE_STATUS" == "completed" ]]; then
-              PIPELINE_RESULT=$(az pipelines runs show \
+      - name: Wait for Azure pipeline run to complete
+        uses: azure/cli@v2
+        with:
+          azcliversion: latest
+          inlineScript: |
+            echo "Waiting for Azure DevOps Pipeline run to complete..."
+            while true; do
+              PIPELINE_STATUS=$(az pipelines runs show \
                 --id ${{ steps.trigger_pipeline.outputs.run_id }} \
                 --org "${{ secrets.ADO_ORG_URL }}" \
                 --project "${{ secrets.ADO_PROJECT }}" \
-                --query "result" -o tsv)
+                --query "status" -o tsv)
 
-              echo "Pipeline completed with result: $PIPELINE_RESULT"
-              if [[ "$PIPELINE_RESULT" == "succeeded" ]]; then
-                exit 0
+              echo "Current pipeline status: $PIPELINE_STATUS"
+
+              if [[ "$PIPELINE_STATUS" == "completed" ]]; then
+                PIPELINE_RESULT=$(az pipelines runs show \
+                  --id ${{ steps.trigger_pipeline.outputs.run_id }} \
+                  --org "${{ secrets.ADO_ORG_URL }}" \
+                  --project "${{ secrets.ADO_PROJECT }}" \
+                  --query "result" -o tsv)
+
+                echo "Pipeline completed with result: $PIPELINE_RESULT"
+                if [[ "$PIPELINE_RESULT" == "succeeded" ]]; then
+                  exit 0
+                else
+                  echo "Azure DevOps Pipeline failed with result: $PIPELINE_RESULT"
+                  exit 1
+                fi
+              elif [[ "$PIPELINE_STATUS" == "cancelling" || "$PIPELINE_STATUS" == "notStarted" || "$PIPELINE_STATUS" == "inProgress" ]]; then
+                sleep 10
               else
-                echo "Azure DevOps Pipeline failed with result: $PIPELINE_RESULT"
+                echo "Azure DevOps Pipeline finished with unexpected status: $PIPELINE_STATUS"
                 exit 1
               fi
-            elif [[ "$PIPELINE_STATUS" == "cancelling" || "$PIPELINE_STATUS" == "notStarted" || "$PIPELINE_STATUS" == "inProgress" ]]; then
-              sleep 10
-            else
-              echo "Azure DevOps Pipeline finished with unexpected status: $PIPELINE_STATUS"
-              exit 1
-            fi
-          done
+            done
 
   release:
     runs-on: ubuntu-latest
